# Generated by Django 4.1.5 on 2023-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Auckland', 'Auckland'), ('Christchurch', 'Christchurch'), ('Queenstown', 'Queenstown')], default='Auckland', max_length=200),
        ),
    ]
