# Generated by Django 4.1.5 on 2023-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_age_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
